// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
	service_name,
	price,
	user_id,
	start_date,
	end_date
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	UserID      uuid.UUID   `json:"user_id"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :one
DELETE FROM subscriptions
WHERE id = $1
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, deleteSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date, created_at, updated_at
FROM subscriptions
WHERE ($1::uuid IS NULL OR user_id = $1::uuid)
	AND ($2::text IS NULL OR service_name ILIKE '%' || $2::text || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListSubscriptionsParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName pgtype.Text `json:"service_name"`
	PageOffset  int32       `json:"page_offset"`
	PageLimit   int32       `json:"page_limit"`
}

func (q *Queries) ListSubscriptions(ctx context.Context, arg ListSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions,
		arg.UserID,
		arg.ServiceName,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSubscriptionsCost = `-- name: SumSubscriptionsCost :one
WITH bounds AS (
	SELECT
		date_trunc('month', $1::date) AS period_start,
		date_trunc('month', $2::date) AS period_end
),
active AS (
	SELECT
		s.price,
		GREATEST(date_trunc('month', s.start_date), b.period_start) AS overlap_start,
		LEAST(date_trunc('month', COALESCE(s.end_date, b.period_end)), b.period_end) AS overlap_end
	FROM subscriptions s
	CROSS JOIN bounds b
	WHERE s.start_date <= b.period_end
		AND (s.end_date IS NULL OR s.end_date >= b.period_start)
		AND ($3::uuid IS NULL OR s.user_id = $3::uuid)
		AND ($4::text IS NULL OR s.service_name ILIKE '%' || $4::text || '%')
)
SELECT COALESCE(
	SUM(
		price * (
			DATE_PART('year', age(overlap_end, overlap_start)) * 12 +
			DATE_PART('month', age(overlap_end, overlap_start)) +
			1
		)
	),
	0
)::bigint AS total_cost
FROM active
`

type SumSubscriptionsCostParams struct {
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	UserID      pgtype.UUID `json:"user_id"`
	ServiceName pgtype.Text `json:"service_name"`
}

func (q *Queries) SumSubscriptionsCost(ctx context.Context, arg SumSubscriptionsCostParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumSubscriptionsCost,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.UserID,
		arg.ServiceName,
	)
	var total_cost int64
	err := row.Scan(&total_cost)
	return total_cost, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
	service_name = $1,
	price = $2,
	start_date = $3,
	end_date = $4,
	updated_at = now()
WHERE id = $5
RETURNING id, service_name, price, user_id, start_date, end_date, created_at, updated_at
`

type UpdateSubscriptionParams struct {
	ServiceName string      `json:"service_name"`
	Price       int32       `json:"price"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
